{% set name = "storylines" %}
{% set version = "0.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fba9af384ad5bf4239022fb1c806b35dd6e97808141ab074ba5dd27f0ea1e2e9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=2.7
    - flit-core >=3.4
    - pip
  run:
    - python >=2.7

test:
  imports:
    - storylines
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/janberges/StoryLines
  summary: Line plots with Python & TikZ
  license: 0BSD
  license_file: LICENSE
  doc_url: https://janberges.github.io/StoryLines
  dev_url: https://github.com/janberges/StoryLines

extra:
  recipe-maintainers:
    - janberges
