{% set name = "storylines" %}
{% set version = "0.18" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8fc24d9581ad572614b1c8ee1aebdda49e64b2c210f4c1db8aedb6bc75b231a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - storylines
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/janberges/StoryLines
  summary: Line plots with Python & TikZ
  license: 0BSD
  license_file: LICENSE
  doc_url: https://janberges.github.io/StoryLines
  dev_url: https://github.com/janberges/StoryLines

extra:
  recipe-maintainers:
    - janberges
